### ISSUE TITLE
GitHub won't display the PDF

### ISSUE THREAD

**Issue by gingerbeardman** [ViGrey/gb-nes-pdf-html-zip#1]
GitHub won't display the PDF, it is considered "invalid".

Not a deal breaker, but thought I would mention it!

![Screen shot 2019-12-04 at 10 22 05](https://user-images.githubusercontent.com/49612/70134437-fed12b00-167f-11ea-9f96-b6cd58a89255.png)

But, nice work on this!

**Comment by ViGrey** [comment]
I'll take a look at it today to see if I have improper pointers in the pdf file.  This issue apparently also exists on a bunch of Android PDF viewers

**Comment by Link2006** [comment]
Attempting to open it in chrome also results in "File is invalid"

**Comment by ViGrey** [comment]
I found a few issues in the PDF file, including forgetting to add an `endobj`, and forgetting to add an xref entry in the xref table.  This issue is now fixed.  The fixed file is now in the `bin` directory of this repository.

**Comment by farmerbb** [comment]
I know this issue is closed now, but FWIW I'm still having trouble displaying the PDF in Adobe Acrobat Reader for Android using the latest version from `master`.

**Comment by ViGrey** [comment]
I'll look into it.

**Comment by ViGrey** [comment]
Issue fixed in 3d9325f9b20fb734895523ef88a735ff28fa6ffd.  Tested on Adobe Acrobat for Android.  I had incorrect assumptions about xref pointers, but that is fixed now.
